
Tutorial.pdf:
	latex Tutorial.tex
	bibtex Tutorial
	latex Tutorial.tex
	latex Tutorial.tex
	dvipdft Tutorial.dvi
	rm -f *.dvi *.aux *.bbl *.blg *.log

clean:
	rm -f *.dvi *.aux *.bbl *.blg *.log *.pdf

