package org.cytoscape.tiedie.internal;

import java.awt.Component;
import javax.swing.Icon;
import org.cytoscape.application.CyApplicationManager;
import org.cytoscape.application.swing.CySwingApplication;
import org.cytoscape.application.swing.CytoPanelComponent;
import org.cytoscape.application.swing.CytoPanelName;



/**
 *
 * @author SrikanthB
 * Creates new form TieDieStartMenu
 */

public class TieDieStartMenu extends javax.swing.JPanel implements CytoPanelComponent {
    
    CyApplicationManager cyApplicationManager;
    CySwingApplication cyDesktopService;
    private TieDieCore tiediecore;
    public CyActivator cyactivator;
    
   
    public TieDieStartMenu(CyActivator cyactivator,TieDieCore tiediecore) {
        initComponents();
        this.cyactivator = cyactivator;
        this.tiediecore = tiediecore;
        cyApplicationManager = tiediecore.getCyApplicationManager();
        cyDesktopService = tiediecore.getCyDesktopService();
       
    }
    
    public Icon getIcon() {
        return null;
    }
    
    public String getTitle() {
        return "TieDIE";
    }
    
    public CytoPanelName getCytoPanelName() {
        return CytoPanelName.WEST;
    }
    
    public Component getComponent() {
        return this;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
